[tool.uv.workspace]
members = [
    "backend",
    "packages/elims-common",
    "packages/elims-raspberry"
]

[tool.uv.sources]
elims-common = { workspace = true }
elims-raspberry = { workspace = true }

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
docs = [
    "greenlet>=3.1.0",
    "mdformat>=0.7.22",
    "mdformat-frontmatter>=2.0.8",
    "mdformat-gfm>=0.4.1",
    "mdformat-tables>=1.0.0",
    "mike>=2.1.3",
    "mkdocs>=1.6.1",
    "mkdocs-glightbox>=0.5.1",
    "mkdocs-material>=9.6.21",
    "mkdocs-mermaid2-plugin>=1.2.2",
    "mkdocs-minify-plugin>=0.8.0",
    "mkdocs-plotly-plugin>=0.1.3",
    "mkdocstrings[python]>=0.30.1",
    "vale>=3.12.0.2",
]


[tool.ruff]
line-length = 180
target-version = "py313"
fix = true
show-fixes = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812", # Allow trailing commas in multi-line constructs
    "D203",   # 1 blank line required before class docstring (conflicts with D211)
    "D213",   # Multi-line docstring summary should start at the second line (conflicts with D212)
    "ISC001", # Allow use of 'isinstance' with a tuple of types
    "S101",   # Use of assert detected. Need to allow assert statements in tests
]

[tool.ruff.lint.per-file-ignores]
"**/tests/**/*.py" = [
    "ANN401",  # Allow typing.Any in tests for mocks
    "PT019",   # Allow pytest fixtures as function arguments (needed for @patch decorator)
]
"packages/**/tests/**/*.py" = [
    "ANN401",  # Allow typing.Any in tests for mocks
    "PT019",   # Allow pytest fixtures as function arguments (needed for @patch decorator)
]

[tool.mypy]
python_version = "3.13"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
pretty = true
plugins = ["pydantic.mypy"]
namespace_packages = true
explicit_package_bases = true

[tool.mdformat]
wrap = 80
end_of_line = "lf"
extensions = [
    "gfm",        # GitHub Flavored Markdown
    "frontmatter", # YAML front matter
    "tables",     # Table formatting
]
