[tool.uv.workspace]
members = [
    "backend",
    "packages/elims-common",
    "packages/elims-raspberry"
]

[tool.uv.sources]
elims-common = { workspace = true }
elims-raspberry = { workspace = true }

[tool.ruff]
line-length = 180
target-version = "py313"
fix = true
show-fixes = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812", # Allow trailing commas in multi-line constructs
    "D203",   # 1 blank line required before class docstring (conflicts with D211)
    "D213",   # Multi-line docstring summary should start at the second line (conflicts with D212)
    "ISC001", # Allow use of 'isinstance' with a tuple of types
    "S101",   # Use of assert detected. Need to allow assert statements in tests
]

[tool.mypy]
python_version = "3.13"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
pretty = true
plugins = ["pydantic.mypy"]
namespace_packages = true
explicit_package_bases = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --cov-report=term-missing"
asyncio_mode = "auto"

[tool.mdformat]
wrap = 80
end_of_line = "lf"
extensions = [
    "gfm",        # GitHub Flavored Markdown
    "frontmatter", # YAML front matter
    "tables",     # Table formatting
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
